### ISSUE TITLE
On Debian Stretch: "No package matching 'libzip2' is available"

### ISSUE THREAD

**Issue by s-t-a-n** [lifeofguenter/ansible-role-php7-fpm#1]
Hi! 

Thanks for writing this ansible role!

It appears libzip2is now deprecated on the Debian Stretch

Error:
`TASK [lifeofguenter.php7-fpm : install dependencies] *******************************
failed: [Testin0] (item=[u'libsystemd0', u'libltdl7', u'libssl1.1', u'libicu57', u'libxml2', u'libbz2-1.0', u'libcurl3', u'libwebp6', u'libpng16-16', u'libfreetype6', u'libmcrypt4', u'libedit2', u'libreadline7', u'libxslt1.1', u'libjpeg62-turbo', u'libzip2', u'libmagickwand-6.q16-3', u'libhiredis0.13', u'libmemcached11', u'libmemcachedutil2']) => {"failed": true, "item": ["libsystemd0", "libltdl7", "libssl1.1", "libicu57", "libxml2", "libbz2-1.0", "libcurl3", "libwebp6", "libpng16-16", "libfreetype6", "libmcrypt4", "libedit2", "libreadline7", "libxslt1.1", "libjpeg62-turbo", "libzip2", "libmagickwand-6.q16-3", "libhiredis0.13", "libmemcached11", "libmemcachedutil2"], "msg": "No package matching 'libzip2' is available"}`

Kernel: 4.9.30-2+deb9u5 
Used ISO: Debian 9.1.0 minimal netinst

Using libzip4 appears to fix the problem :)

**Comment by lifeofguenter** [comment]
thanks @pafklapper !
